version: '3.7'

volumes:
  teleport:

networks:
  teleportData:

services:
  Teleport:
    image: kristianfoss/programs-teleport:alpine-teleport
    tty: true
    stdin_open: true
    command: ['start']
    ports:
      - 3080:3080
      - 3023:3023
      - 3025:3025
