version: '3.7'

networks:
  publicWeb:

volumes:
  tlsCertificates:
  bitwardenData:
  bitwardenBackups:
  dnsZones:
  dnsConfig:
  subscriberData:

services:
  # Caddy Reverse Proxy to handle all traffic into the VPS1 Stack
  #
  # Repo: https://github.com/caddyserver/caddy
  Web:
    image: hectormolinero/caddy2:v17-amd64
    restart: unless-stopped
    command: ['run', '--config', '/etc/Caddy/Caddyfile.json']
    volumes:
      - ./Caddyfile.json:/etc/Caddy/Caddyfile.json:ro
      - tlsCertificates:/TLS:ro
    ports:
      - 80:8080
      - 443:8443/tcp
      - 443:8443/udp
    networks:
      - publicWeb
    labels:
      com.ouroboros.enable: 'true'
      com.distributed-dns.web: 'true'

  # Script that checks for updates to docker containers and recreates an identical container with new image if there is an update.
  #
  # I currently have it setup to only update containers with the docker tag of `com.ouroboros.enable: 'true'`
  #
  # Repo: https://github.com/pyouroboros/ouroboros
  ouroboros:
    image: pyouroboros/ouroboros
    restart: unless-stopped
    container_name: ouroboros
    hostname: ouroboros
    env_file: ENVs/Ouroboros.env
    environment:
      CLEANUP: 'true'
      LOG_LEVEL: 'error'
      SELF_UPDATE: 'true'
      LABEL_ENABLE: 'true'
      LABELS_ONLY: 'true'
      TZ: 'America/Winnipeg'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/root/.docker/config.json:ro

  # pfCarper used to automatically assign a DigitalOcean Floating IP to tagged droplets when the active droplet stops responding
  # at a port, default `443`
  #
  # Repo: https://github.com/K-FOSS/pfCarper
  pfCarper:
    image: docker.pkg.github.com/k-foss/pfcarper/pfcarper
    restart: unless-stopped
    env_file: ENVs/pfCarper.env
    labels:
      com.ouroboros.enable: 'true'

  # Self hosted speed test to test connection to VPS and for friends and clients to test their network connection
  #
  # Repo: https://github.com/librespeed/speedtest
  speedtest-kjdev:
    image: adolfintel/speedtest
    restart: unless-stopped
    networks:
      - publicWeb
    environment:
      MODE: 'standalone'
      TELEMETRY: 'true'
      ENABLE_ID_OBFUSCATION: 'true'
    labels:
      com.ouroboros.enable: 'true'

  # Self hosted password manager with more features then LastPass
  #
  # I'm running the third party unofficcal BitwardenRS Server & Image
  #
  # Offical Site: https://bitwarden.com/
  # Repo: https://github.com/dani-garcia/bitwarden_rs
  bitwarden-kjdev:
    image: bitwardenrs/server:alpine
    restart: unless-stopped
    env_file: ./ENVs/Bitwarden.env
    volumes:
      - bitwardenData:/data
    networks:
      - publicWeb
    environment:
      WEBSOCKET_ENABLED: 'true' # Required to use websockets
      SIGNUPS_ALLOWED: 'true' # set to false to disable signups
      LOG_LEVEL: 'off'
    labels:
      com.ouroboros.enable: 'true'

  bitwarden-kjdev-backup:
    image: bruceforce/bw_backup
    restart: on-failure
    init: true
    depends_on:
      - bitwarden-kjdev
    volumes:
      - bitwardenData:/data:ro
      - bitwardenBackups:/backups
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_FILE: '/data/db.sqlite3'
      BACKUP_FILE: '/backups/backup.sqlite3'
      CRON_TIME: '0 * * * *'
      TIMESTAMP: 'true'
      UID: '0'
      GID: '0'

  # BIND9 Server for serving the Zones from Distributed DNS. Zones are fetched and container is controlled by the DNSDL Service
  ns1-kjdev:
    image: resystit/bind9:latest
    restart: unless-stopped
    depends_on:
      - DNSDL
    volumes:
      - dnsZones:/zones:ro
      - dnsConfig:/etc/bind:ro
    ports:
      - 53:53/udp
    labels:
      com.distributed-dns.bind: 'true'
      com.ouroboros.enable: 'true'

  SubscriberDL:
    image: docker.pkg.github.com/kristianfjones/distributed-dns/distributed-dns-subscriberdl
    restart: unless-stopped
    env_file: ENVs/SubscriberDL.env
    environment:
      API_URL: 'https://dns.kristianjones.dev'
    volumes:
      - subscriberData:/data/State
      - dnsZones:/data/Zones
      - tlsCertificates:/data/TLS
      - dnsConfig:/data/BIND
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      com.ouroboros.enable: 'true'
