version: '3.7'

volumes:
  dockerSocket:
    external:
      name: docker-socket

services:
  DockerDaemon:
    image: kristianfoss/programs-docker:alpine-dockerd-lab
    privileged: true
    build:
      context: ./Docker/
      target: dockerd
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    volumes:
      - dockerSocket:/var/run
      - /var/lib/docker/aufs/diff:/var/lib/docker/aufs/diff

  Docker:
    image: kristianfoss/lab/programs-docker:dockercli
    entrypoint: ['/bin/sh']
    stdin_open: true
    # command: ['buildx', 'bake', '-f', './docker-compose.build.yml']
    working_dir: /workspace
    depends_on:
      - DockerDaemon
    build:
      context: ./Docker/
      target: docker
    volumes:
      - dockerSocket:/var/run
      - ../../:/workspace
