version: '3.8'

networks:
  publicWeb:
  internalDatabase:

volumes:
  databaseData:

services:
  Web:
    image: caddy/caddy:scratch
    restart: unless-stopped
    command: ['caddy', 'run', '--config', '/etc/caddy/Caddyfile.json']
    networks:
      - publicWeb
    ports:
      - 8080:8080
    volumes:
      - ./Caddyfile.json:/etc/caddy/Caddyfile.json:ro

  pgWeb:
    image: kristianfoss/programs-pgweb:scratch
    restart: unless-stopped
    command: ['--bind=0.0.0.0', '--listen=8080']
    depends_on:
      - database
    environment:
      DATABASE_URL: 'postgres://postgres:pgpass@database:5432/demo_data?sslmode=disable'
    networks:
      - publicWeb
      - internalDatabase

  database:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: demo_data
    networks:
      - internalDatabase
    volumes:
      - databaseData:/var/lib/postgresql/data
