ARG BASE_REPO='alpine'
ARG ALPINE_BASE_TAG='latest'
ARG ALPINE_PKGS=''

ARG IMG_CMD

FROM ${ALPINE_BASE_REPO}:${ALPINE_BASE_TAG}
ARG ALPINE_BASE_REPO
ARG ALPINE_BASE_TAG
ARG ALPINE_PKGS
ARG APK_ARGS=""

ARG IMG_CMD


ENV PKGS ${ALPINE_PKGS:-""}
ENV APK_ARGS ${APK_ARGS}

ENV CMD ${IMG_CMD:-[ "/bin/sh", "-s"]}

RUN apk add --no-cache ${APK_ARGS} ${PKGS}

ENTRYPOINT [  ]
CMD ${CMD}