version: '3.8'

volumes:
  teleportData:
  teleportProxyData:
  teleportNodeData:

networks:
  publicWeb:

services:
  Web:
    image: caddy/caddy:scratch
    restart: unless-stopped
    command: ['caddy', 'run', '--config', '/etc/caddy/Caddyfile.json']
    volumes:
      - ./Caddyfile.json:/etc/caddy/Caddyfile.json:ro
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: udp
        mode: host
    networks:
      - publicWeb

  Teleport:
    image: kristianfoss/programs-teleport:alpine-teleport
    command:
      [
        'start',
        '--config',
        '/etc/Teleport.yaml',
        '--insecure',
        '--insecure-no-tls',
      ]
    volumes:
      - ./Teleport.yaml:/etc/Teleport.yaml:ro
      - teleportData:/var/lib/teleport
    ports:
      - 3080:3080
      - 3023:3023
      - 3025:3025
    networks:
      - publicWeb

  TeleportProxy:
    image: kristianfoss/programs-teleport:alpine-teleport
    command:
      ['start', '--config', '/etc/TeleportProxy.yaml', '--insecure', '-d']
    volumes:
      - ./TeleportProxy.yaml:/etc/TeleportProxy.yaml:ro
      - teleportProxyData:/var/lib/teleport
    networks:
      - publicWeb

  TeleportNode:
    build:
      context: ./Node
    image: kristianfoss/programs-teleport:test-node
    command: ['start', '--config', '/etc/TeleportNode.yaml', '--insecure', '-d']
    volumes:
      - ./TeleportNode.yaml:/etc/TeleportNode.yaml:ro
      - teleportNodeData:/var/lib/teleport
    networks:
      - publicWeb
