version: '3.8'

networks:
  publicWeb:

volumes:
  dockerSocket:

services:
  Web:
    image: caddy/caddy:scratch
    restart: unless-stopped
    command: ['caddy', 'run', '--config', '/etc/caddy/Caddyfile.json']
    volumes:
      - ./Caddyfile.json:/etc/caddy/Caddyfile.json:ro
    networks:
      - publicWeb
    ports:
      - 8080:8080

  Cadvisor:
    image: kristianfoss/programs-cadvisor:cadvisor-main-scratch
    restart: unless-stopped
    command: ['-logtostderr', '-docker_only']
    user: root
    volumes:
      - dockerSocket:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - publicWeb

  DockerD:
    image: kristianfoss/programs-docker:dockerd-rootless-alpine
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - dockerSocket:/run/user/1000

  Shell:
    image: kristianfoss/programs-docker:docker-alpine
    tty: true
    stdin_open: true
    entrypoint: ['/bin/sh', '-i']
    volumes:
      - dockerSocket:/var/run
