name: Push

on: [push, pull_request]

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Images
        run: ./bin/buildPush.sh
        working-directory: ./Images
