name: Push

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '* 23 * * *'

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Images
        run: ./bin/buildPush.sh
        working-directory: ./Images
        env:
          USERNAME: kristianfjones
          PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
